#!/usr/bin/env python3
"""Emit SwingTwistKusudama/Humanoid.lean from data/humanoid_cones.parquet.

The four rich multi-cone joints captured from the live humanoid rig (LeftLowerArm, LeftHand,
LeftFoot, Head) become `humanoidJoints : List (Nat × Nat × String × List KCone)`. Cone centers are
the engine's own unit vectors and radii are radians (get_cone_radius), so KCone.r takes them as-is.

Re-run after re-dumping the scene. Keeps the Lean constants in lockstep with the Parquet ground truth.
"""
import os
import duckdb

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")
OUT = os.path.join(ROOT, "SwingTwistKusudama", "Humanoid.lean")

# (setting, joint, label) — the joints mirrored in data/humanoid_ground_truth.parquet
PICKS = [(0, 1, "LeftLowerArm"), (0, 2, "LeftHand"), (2, 2, "LeftFoot"), (4, 4, "Head")]

con = duckdb.connect()


def lit(x):
    return repr(float(x))


lines = [
    "import SwingTwistKusudama.Kusudama",
    "",
    "/-!",
    "# Humanoid — the live humanoid rig's rich kusudama joints (generated).",
    "",
    "Generated by `scripts/gen_humanoid_lean.py` from `data/humanoid_cones.parquet`, itself dumped",
    "from the running editor (`GeneralSkeleton/HumanoidRomIK`) via the godot MCP bridge. Cone centers",
    "are unit vectors and radii are radians, straight from the engine. Do not edit by hand; re-run the",
    "generator after re-dumping the scene.",
    "-/",
    "",
    "namespace SwingTwistKusudama",
    "",
    "/-- The rich multi-cone joints (setting, joint, label, cones), mirroring",
    "`data/humanoid_ground_truth.parquet`. -/",
    "def humanoidJoints : List (Nat × Nat × String × List KCone) :=",
]

joint_strs = []
for s, j, label in PICKS:
    rows = con.execute(
        "SELECT cx,cy,cz,radius FROM read_parquet(?) WHERE setting=? AND joint=? ORDER BY cone",
        [os.path.join(DATA, "humanoid_cones.parquet"), s, j],
    ).fetchall()
    cones = ", ".join(
        f"⟨⟨{lit(cx)}, {lit(cy)}, {lit(cz)}⟩, {lit(r)}⟩" for (cx, cy, cz, r) in rows
    )
    joint_strs.append(f'    ({s}, {j}, \"{label}\",\n      [ {cones} ])')

lines.append("  [ " + "\n  , ".join(s.lstrip() for s in joint_strs).replace("\n  , ", "\n  , ") + " ]")
# rebuild cleanly: list with leading markers
body = "  [ " + "\n  , ".join(js[4:] for js in joint_strs) + " ]"
lines[-1] = body
lines += ["", "end SwingTwistKusudama", ""]

with open(OUT, "w") as f:
    f.write("\n".join(lines))

total = con.execute(
    "SELECT count(*) FROM read_parquet(?) WHERE (setting,joint) IN (VALUES (0,1),(0,2),(2,2),(4,4))",
    [os.path.join(DATA, "humanoid_cones.parquet")],
).fetchone()[0]
print(f"wrote {OUT} ({len(PICKS)} joints, {total} cones)")
